FROM php:8.3-fpm

COPY php.ini /usr/local/etc/php/

# UID を受け取る(wsl対応、ファイル権限問題対策)
# UID 宣言のみ
ARG UID

# 基本拡張とビルドに必要なツール群
RUN apt update \
  && apt install -y default-mysql-client zlib1g-dev libzip-dev unzip \
  && docker-php-ext-install pdo_mysql zip

# Xdebug を入れて有効化（ロード用 ini が自動生成される）
# pecl: PECL（PHP Extension Community Library） の略
#       PHP の公式拡張モジュールをインターネット経由で取得・インストールするためのコマンドラインツール
RUN pecl install xdebug && docker-php-ext-enable xdebug

# 追加設定は別ファイルに（任意の名前でOK）
# conf.d にある .ini が数字順に後から読むので、99-xdebug.ini は最後に読まれる
# このファイルには、 Xdebug の挙動を制御する設定
RUN { \
  echo "[xdebug]"; \
  echo "xdebug.mode=debug,develop"; \
  echo "xdebug.start_with_request=yes"; \
  echo "xdebug.client_host=host.docker.internal"; \
  echo "xdebug.client_port=9003"; \
  echo "xdebug.log_level=0"; \
} > /usr/local/etc/php/conf.d/99-xdebug.ini

# UID をwww-dataに適用 (wsl対応、ファイル権限問題対策)
RUN [ -n "${UID:-}" ] && usermod -u "${UID}" www-data
# もし UID が設定されていれば → usermod 実行
# もし UID が空なら → 何もしない（エラーも出ない）

# Composer
RUN curl -sS https://getcomposer.org/installer | php \
  && mv composer.phar /usr/local/bin/composer \
  && composer self-update

WORKDIR /var/www

# これを最後に追加
USER www-data

